SELECT  [rowid_]
      ,[CustomerID]
      ,[Timestamp]
      ,[Channel]
      ,[Direction]
      ,[Status]
      ,[Duration]
      ,[inserted_date]
  FROM [Sigma_Connected].[dbo].[OLE DB Destination_backup]
